/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *titulo;
    QLabel *PrimerJugador;
    QLabel *SegundoJugador;
    QFrame *frame;
    QPushButton *carta1;
    QPushButton *carta4;
    QPushButton *carta5;
    QPushButton *carta6;
    QPushButton *carta7;
    QPushButton *carta23;
    QPushButton *carta24;
    QPushButton *carta25;
    QPushButton *carta21;
    QPushButton *carta27;
    QPushButton *carta26;
    QPushButton *carta13;
    QPushButton *carta15;
    QPushButton *carta16;
    QPushButton *carta14;
    QPushButton *carta11;
    QPushButton *carta17;
    QPushButton *carta34;
    QPushButton *carta37;
    QPushButton *carta36;
    QPushButton *carta31;
    QPushButton *carta35;
    QPushButton *carta33;
    QPushButton *carta43;
    QPushButton *carta46;
    QPushButton *carta45;
    QPushButton *carta44;
    QPushButton *carta47;
    QPushButton *carta41;
    QPushButton *carta22;
    QPushButton *carta32;
    QPushButton *carta2;
    QPushButton *carta12;
    QPushButton *carta42;
    QPushButton *carta48;
    QPushButton *carta28;
    QPushButton *carta18;
    QPushButton *carta8;
    QPushButton *carta38;
    QPushButton *carta49;
    QPushButton *carta29;
    QPushButton *carta19;
    QPushButton *carta9;
    QPushButton *carta39;
    QPushButton *carta50;
    QPushButton *carta30;
    QPushButton *carta20;
    QPushButton *carta10;
    QPushButton *carta40;
    QPushButton *carta59;
    QPushButton *carta60;
    QPushButton *carta56;
    QPushButton *carta57;
    QPushButton *carta58;
    QPushButton *carta55;
    QPushButton *carta51;
    QPushButton *carta52;
    QPushButton *carta54;
    QPushButton *carta53;
    QPushButton *carta69;
    QPushButton *carta70;
    QPushButton *carta66;
    QPushButton *carta67;
    QPushButton *carta68;
    QPushButton *carta65;
    QPushButton *carta61;
    QPushButton *carta62;
    QPushButton *carta64;
    QPushButton *carta63;
    QPushButton *carta3;
    QLabel *cronometro;
    QLabel *Puntaje1;
    QLabel *Puntaje2;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1033, 770);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        titulo = new QLabel(centralwidget);
        titulo->setObjectName(QString::fromUtf8("titulo"));
        titulo->setGeometry(QRect(20, 10, 171, 31));
        QFont font;
        font.setFamily(QString::fromUtf8("Ubuntu Condensed"));
        font.setPointSize(20);
        font.setBold(true);
        font.setItalic(true);
        font.setWeight(75);
        titulo->setFont(font);
        PrimerJugador = new QLabel(centralwidget);
        PrimerJugador->setObjectName(QString::fromUtf8("PrimerJugador"));
        PrimerJugador->setGeometry(QRect(10, 660, 67, 17));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Ubuntu Condensed"));
        font1.setBold(true);
        font1.setItalic(true);
        font1.setWeight(75);
        PrimerJugador->setFont(font1);
        SegundoJugador = new QLabel(centralwidget);
        SegundoJugador->setObjectName(QString::fromUtf8("SegundoJugador"));
        SegundoJugador->setGeometry(QRect(10, 700, 67, 17));
        SegundoJugador->setFont(font1);
        frame = new QFrame(centralwidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(10, 50, 1011, 591));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        carta1 = new QPushButton(frame);
        carta1->setObjectName(QString::fromUtf8("carta1"));
        carta1->setGeometry(QRect(10, 20, 91, 71));
        carta4 = new QPushButton(frame);
        carta4->setObjectName(QString::fromUtf8("carta4"));
        carta4->setGeometry(QRect(310, 20, 91, 71));
        carta5 = new QPushButton(frame);
        carta5->setObjectName(QString::fromUtf8("carta5"));
        carta5->setGeometry(QRect(410, 20, 91, 71));
        carta6 = new QPushButton(frame);
        carta6->setObjectName(QString::fromUtf8("carta6"));
        carta6->setGeometry(QRect(510, 20, 91, 71));
        carta7 = new QPushButton(frame);
        carta7->setObjectName(QString::fromUtf8("carta7"));
        carta7->setGeometry(QRect(610, 20, 91, 71));
        carta23 = new QPushButton(frame);
        carta23->setObjectName(QString::fromUtf8("carta23"));
        carta23->setGeometry(QRect(210, 180, 91, 71));
        carta24 = new QPushButton(frame);
        carta24->setObjectName(QString::fromUtf8("carta24"));
        carta24->setGeometry(QRect(310, 180, 91, 71));
        carta25 = new QPushButton(frame);
        carta25->setObjectName(QString::fromUtf8("carta25"));
        carta25->setGeometry(QRect(410, 180, 91, 71));
        carta21 = new QPushButton(frame);
        carta21->setObjectName(QString::fromUtf8("carta21"));
        carta21->setGeometry(QRect(10, 180, 91, 71));
        carta27 = new QPushButton(frame);
        carta27->setObjectName(QString::fromUtf8("carta27"));
        carta27->setGeometry(QRect(610, 180, 91, 71));
        carta26 = new QPushButton(frame);
        carta26->setObjectName(QString::fromUtf8("carta26"));
        carta26->setGeometry(QRect(510, 180, 91, 71));
        carta13 = new QPushButton(frame);
        carta13->setObjectName(QString::fromUtf8("carta13"));
        carta13->setGeometry(QRect(210, 100, 91, 71));
        carta15 = new QPushButton(frame);
        carta15->setObjectName(QString::fromUtf8("carta15"));
        carta15->setGeometry(QRect(410, 100, 91, 71));
        carta16 = new QPushButton(frame);
        carta16->setObjectName(QString::fromUtf8("carta16"));
        carta16->setGeometry(QRect(510, 100, 91, 71));
        carta14 = new QPushButton(frame);
        carta14->setObjectName(QString::fromUtf8("carta14"));
        carta14->setGeometry(QRect(310, 100, 91, 71));
        carta11 = new QPushButton(frame);
        carta11->setObjectName(QString::fromUtf8("carta11"));
        carta11->setGeometry(QRect(10, 100, 91, 71));
        carta17 = new QPushButton(frame);
        carta17->setObjectName(QString::fromUtf8("carta17"));
        carta17->setGeometry(QRect(610, 100, 91, 71));
        carta34 = new QPushButton(frame);
        carta34->setObjectName(QString::fromUtf8("carta34"));
        carta34->setGeometry(QRect(310, 260, 91, 71));
        carta37 = new QPushButton(frame);
        carta37->setObjectName(QString::fromUtf8("carta37"));
        carta37->setGeometry(QRect(610, 260, 91, 71));
        carta36 = new QPushButton(frame);
        carta36->setObjectName(QString::fromUtf8("carta36"));
        carta36->setGeometry(QRect(510, 260, 91, 71));
        carta31 = new QPushButton(frame);
        carta31->setObjectName(QString::fromUtf8("carta31"));
        carta31->setGeometry(QRect(10, 260, 91, 71));
        carta35 = new QPushButton(frame);
        carta35->setObjectName(QString::fromUtf8("carta35"));
        carta35->setGeometry(QRect(410, 260, 91, 71));
        carta33 = new QPushButton(frame);
        carta33->setObjectName(QString::fromUtf8("carta33"));
        carta33->setGeometry(QRect(210, 260, 91, 71));
        carta43 = new QPushButton(frame);
        carta43->setObjectName(QString::fromUtf8("carta43"));
        carta43->setGeometry(QRect(210, 340, 91, 71));
        carta46 = new QPushButton(frame);
        carta46->setObjectName(QString::fromUtf8("carta46"));
        carta46->setGeometry(QRect(510, 340, 91, 71));
        carta45 = new QPushButton(frame);
        carta45->setObjectName(QString::fromUtf8("carta45"));
        carta45->setGeometry(QRect(410, 340, 91, 71));
        carta44 = new QPushButton(frame);
        carta44->setObjectName(QString::fromUtf8("carta44"));
        carta44->setGeometry(QRect(310, 340, 91, 71));
        carta47 = new QPushButton(frame);
        carta47->setObjectName(QString::fromUtf8("carta47"));
        carta47->setGeometry(QRect(610, 340, 91, 71));
        carta41 = new QPushButton(frame);
        carta41->setObjectName(QString::fromUtf8("carta41"));
        carta41->setGeometry(QRect(10, 340, 91, 71));
        carta22 = new QPushButton(frame);
        carta22->setObjectName(QString::fromUtf8("carta22"));
        carta22->setGeometry(QRect(110, 180, 91, 71));
        carta32 = new QPushButton(frame);
        carta32->setObjectName(QString::fromUtf8("carta32"));
        carta32->setGeometry(QRect(110, 260, 91, 71));
        carta2 = new QPushButton(frame);
        carta2->setObjectName(QString::fromUtf8("carta2"));
        carta2->setGeometry(QRect(110, 20, 91, 71));
        carta12 = new QPushButton(frame);
        carta12->setObjectName(QString::fromUtf8("carta12"));
        carta12->setGeometry(QRect(110, 100, 91, 71));
        carta42 = new QPushButton(frame);
        carta42->setObjectName(QString::fromUtf8("carta42"));
        carta42->setGeometry(QRect(110, 340, 91, 71));
        carta48 = new QPushButton(frame);
        carta48->setObjectName(QString::fromUtf8("carta48"));
        carta48->setGeometry(QRect(710, 340, 91, 71));
        carta28 = new QPushButton(frame);
        carta28->setObjectName(QString::fromUtf8("carta28"));
        carta28->setGeometry(QRect(710, 180, 91, 71));
        carta18 = new QPushButton(frame);
        carta18->setObjectName(QString::fromUtf8("carta18"));
        carta18->setGeometry(QRect(710, 100, 91, 71));
        carta8 = new QPushButton(frame);
        carta8->setObjectName(QString::fromUtf8("carta8"));
        carta8->setGeometry(QRect(710, 20, 91, 71));
        carta38 = new QPushButton(frame);
        carta38->setObjectName(QString::fromUtf8("carta38"));
        carta38->setGeometry(QRect(710, 260, 91, 71));
        carta49 = new QPushButton(frame);
        carta49->setObjectName(QString::fromUtf8("carta49"));
        carta49->setGeometry(QRect(810, 340, 91, 71));
        carta29 = new QPushButton(frame);
        carta29->setObjectName(QString::fromUtf8("carta29"));
        carta29->setGeometry(QRect(810, 180, 91, 71));
        carta19 = new QPushButton(frame);
        carta19->setObjectName(QString::fromUtf8("carta19"));
        carta19->setGeometry(QRect(810, 100, 91, 71));
        carta9 = new QPushButton(frame);
        carta9->setObjectName(QString::fromUtf8("carta9"));
        carta9->setGeometry(QRect(810, 20, 91, 71));
        carta39 = new QPushButton(frame);
        carta39->setObjectName(QString::fromUtf8("carta39"));
        carta39->setGeometry(QRect(810, 260, 91, 71));
        carta50 = new QPushButton(frame);
        carta50->setObjectName(QString::fromUtf8("carta50"));
        carta50->setGeometry(QRect(910, 340, 91, 71));
        carta30 = new QPushButton(frame);
        carta30->setObjectName(QString::fromUtf8("carta30"));
        carta30->setGeometry(QRect(910, 180, 91, 71));
        carta20 = new QPushButton(frame);
        carta20->setObjectName(QString::fromUtf8("carta20"));
        carta20->setGeometry(QRect(910, 100, 91, 71));
        carta10 = new QPushButton(frame);
        carta10->setObjectName(QString::fromUtf8("carta10"));
        carta10->setGeometry(QRect(910, 20, 91, 71));
        carta40 = new QPushButton(frame);
        carta40->setObjectName(QString::fromUtf8("carta40"));
        carta40->setGeometry(QRect(910, 260, 91, 71));
        carta59 = new QPushButton(frame);
        carta59->setObjectName(QString::fromUtf8("carta59"));
        carta59->setGeometry(QRect(810, 420, 91, 71));
        carta60 = new QPushButton(frame);
        carta60->setObjectName(QString::fromUtf8("carta60"));
        carta60->setGeometry(QRect(910, 420, 91, 71));
        carta56 = new QPushButton(frame);
        carta56->setObjectName(QString::fromUtf8("carta56"));
        carta56->setGeometry(QRect(510, 420, 91, 71));
        carta57 = new QPushButton(frame);
        carta57->setObjectName(QString::fromUtf8("carta57"));
        carta57->setGeometry(QRect(610, 420, 91, 71));
        carta58 = new QPushButton(frame);
        carta58->setObjectName(QString::fromUtf8("carta58"));
        carta58->setGeometry(QRect(710, 420, 91, 71));
        carta55 = new QPushButton(frame);
        carta55->setObjectName(QString::fromUtf8("carta55"));
        carta55->setGeometry(QRect(410, 420, 91, 71));
        carta51 = new QPushButton(frame);
        carta51->setObjectName(QString::fromUtf8("carta51"));
        carta51->setGeometry(QRect(10, 420, 91, 71));
        carta52 = new QPushButton(frame);
        carta52->setObjectName(QString::fromUtf8("carta52"));
        carta52->setGeometry(QRect(110, 420, 91, 71));
        carta54 = new QPushButton(frame);
        carta54->setObjectName(QString::fromUtf8("carta54"));
        carta54->setGeometry(QRect(310, 420, 91, 71));
        carta53 = new QPushButton(frame);
        carta53->setObjectName(QString::fromUtf8("carta53"));
        carta53->setGeometry(QRect(210, 420, 91, 71));
        carta69 = new QPushButton(frame);
        carta69->setObjectName(QString::fromUtf8("carta69"));
        carta69->setGeometry(QRect(810, 500, 91, 71));
        carta70 = new QPushButton(frame);
        carta70->setObjectName(QString::fromUtf8("carta70"));
        carta70->setGeometry(QRect(910, 500, 91, 71));
        carta66 = new QPushButton(frame);
        carta66->setObjectName(QString::fromUtf8("carta66"));
        carta66->setGeometry(QRect(510, 500, 91, 71));
        carta67 = new QPushButton(frame);
        carta67->setObjectName(QString::fromUtf8("carta67"));
        carta67->setGeometry(QRect(610, 500, 91, 71));
        carta68 = new QPushButton(frame);
        carta68->setObjectName(QString::fromUtf8("carta68"));
        carta68->setGeometry(QRect(710, 500, 91, 71));
        carta65 = new QPushButton(frame);
        carta65->setObjectName(QString::fromUtf8("carta65"));
        carta65->setGeometry(QRect(410, 500, 91, 71));
        carta61 = new QPushButton(frame);
        carta61->setObjectName(QString::fromUtf8("carta61"));
        carta61->setGeometry(QRect(10, 500, 91, 71));
        carta62 = new QPushButton(frame);
        carta62->setObjectName(QString::fromUtf8("carta62"));
        carta62->setGeometry(QRect(110, 500, 91, 71));
        carta64 = new QPushButton(frame);
        carta64->setObjectName(QString::fromUtf8("carta64"));
        carta64->setGeometry(QRect(310, 500, 91, 71));
        carta63 = new QPushButton(frame);
        carta63->setObjectName(QString::fromUtf8("carta63"));
        carta63->setGeometry(QRect(210, 500, 91, 71));
        carta3 = new QPushButton(frame);
        carta3->setObjectName(QString::fromUtf8("carta3"));
        carta3->setGeometry(QRect(210, 20, 91, 71));
        cronometro = new QLabel(centralwidget);
        cronometro->setObjectName(QString::fromUtf8("cronometro"));
        cronometro->setGeometry(QRect(646, 20, 121, 20));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Ubuntu Condensed"));
        font2.setBold(true);
        font2.setWeight(75);
        cronometro->setFont(font2);
        Puntaje1 = new QLabel(centralwidget);
        Puntaje1->setObjectName(QString::fromUtf8("Puntaje1"));
        Puntaje1->setGeometry(QRect(70, 660, 67, 17));
        Puntaje2 = new QLabel(centralwidget);
        Puntaje2->setObjectName(QString::fromUtf8("Puntaje2"));
        Puntaje2->setGeometry(QRect(70, 700, 67, 17));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1033, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        titulo->setText(QApplication::translate("MainWindow", "Memory Game", nullptr));
        PrimerJugador->setText(QApplication::translate("MainWindow", "Player 1:", nullptr));
        SegundoJugador->setText(QApplication::translate("MainWindow", "Player 2:", nullptr));
        carta1->setText(QString());
        carta4->setText(QString());
        carta5->setText(QString());
        carta6->setText(QString());
        carta7->setText(QString());
        carta23->setText(QString());
        carta24->setText(QString());
        carta25->setText(QString());
        carta21->setText(QString());
        carta27->setText(QString());
        carta26->setText(QString());
        carta13->setText(QString());
        carta15->setText(QString());
        carta16->setText(QString());
        carta14->setText(QString());
        carta11->setText(QString());
        carta17->setText(QString());
        carta34->setText(QString());
        carta37->setText(QString());
        carta36->setText(QString());
        carta31->setText(QString());
        carta35->setText(QString());
        carta33->setText(QString());
        carta43->setText(QString());
        carta46->setText(QString());
        carta45->setText(QString());
        carta44->setText(QString());
        carta47->setText(QString());
        carta41->setText(QString());
        carta22->setText(QString());
        carta32->setText(QString());
        carta2->setText(QString());
        carta12->setText(QString());
        carta42->setText(QString());
        carta48->setText(QString());
        carta28->setText(QString());
        carta18->setText(QString());
        carta8->setText(QString());
        carta38->setText(QString());
        carta49->setText(QString());
        carta29->setText(QString());
        carta19->setText(QString());
        carta9->setText(QString());
        carta39->setText(QString());
        carta50->setText(QString());
        carta30->setText(QString());
        carta20->setText(QString());
        carta10->setText(QString());
        carta40->setText(QString());
        carta59->setText(QString());
        carta60->setText(QString());
        carta56->setText(QString());
        carta57->setText(QString());
        carta58->setText(QString());
        carta55->setText(QString());
        carta51->setText(QString());
        carta52->setText(QString());
        carta54->setText(QString());
        carta53->setText(QString());
        carta69->setText(QString());
        carta70->setText(QString());
        carta66->setText(QString());
        carta67->setText(QString());
        carta68->setText(QString());
        carta65->setText(QString());
        carta61->setText(QString());
        carta62->setText(QString());
        carta64->setText(QString());
        carta63->setText(QString());
        carta3->setText(QString());
        cronometro->setText(QApplication::translate("MainWindow", "Cron\303\263metro", nullptr));
        Puntaje1->setText(QApplication::translate("MainWindow", "0", nullptr));
        Puntaje2->setText(QApplication::translate("MainWindow", "0", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
